<?php

require_once dirname(__FILE__) . '/../ibm_i_px.php';

/**
 * Test class for IbmIPxException.
 * Generated by PHPUnit on 2011-04-06 at 11:18:26.
 */
class IbmIPxExceptionTest extends PHPUnit_Framework_TestCase {

  /**
   * @var IbmIPxException
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp() {
    $this->object = new IbmIPxException;
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown() {

  }

  /**
   * @todo Implement testSetLogger().
   */
  public function testSetLogger() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

}

?>
